data:
  image: tropicloud/submarine
  command: true
  volumes:
  - /home/wordpress
  - /var/wps/ssl:/home/wordpress/conf/ssl
submarine:
  image: tropicloud/submarine
  volumes_from:
  - data
  external_links:
  - submarine_mariadb_1:mysql
  - submarine_memcached_1:memcached
  - submarine_redis_1:redis
  env_file: .env
  stdin_open: true
