#!/bin/sh

case $@ in
	reboot)	echo "Reboot!"
	;;
esac

sudo rm -rf /wps/run
sudo kill -9 -1

if [[  $WPS_RESTART == 'true'  ]]; then
	echo "Restart!"
	/usr/bin/wps mount
	exec sudo s6-svscan /wps/run
fi

exit 0