#!/bin/sh

case $@ in
	reboot)	echo "Reboot!"
	;;
esac

sudo rm -rf $run
sudo kill -9 -1

if [[  $WPS_RESTART == 'true'  ]]; then
	cp -R $conf/s6 $run
	echo "Restart!"
	exec sudo s6-svscan $run
fi

exit 0